import MarketingWord from "@/components/marketing-word/marketing-word";
import PageBanner from "@/components/page-banner";
import Projets from "@/components/projet-long-term/projets";
import { Metadata } from "next";



export const metadata: Metadata = {
    title: "Projet À Long Terme",
    description: "Generated by create next app",
  };
  
export default  function ProjetALongTerm(){
    return (
       <>
            <PageBanner image="/assets/img/contactez-nous.JPG" title="Projet à long terme" />
            <Projets/>
            <MarketingWord/>
       </>
    )
}